version: 1
formatters:
  simple:
    format: '%(message)s'
  error:
    format: '%(asctime)s %(name)s %(processName)s: %(levelname)s: %(message)s'
handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: simple
    stream: ext://sys.stdout
  info_file:
    class: logging.handlers.TimedRotatingFileHandler
    filename: logs/satosa_simple.log
    when: midnight
    encoding: utf8
    level: INFO
    backupCount: 5
    formatter: simple
  error_file:
    class: logging.handlers.RotatingFileHandler
    filename: logs/satosa_simple.log
    level: ERROR
    encoding: utf8
    maxBytes: 10485760 # 10MB
    backupCount: 20
    formatter: error
loggers:
  simpleExample:
    level: DEBUG
    handlers: [info_file, error_file]
    propagate: yes
root:
  level: DEBUG
  handlers: [console]
